spring.application.name=savings-account
spring.mvc.problemdetails.enabled=true

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=coding_assessment
spring.datasource.username=savings_user
spring.datasource.password=${DATABASE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=coding_assessment
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
